# Generated by Django 5.2.7 on 2025-11-03 14:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contactquery_bulkorder'),
        ('orders', '0005_alter_order_platform_fee'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_payment_method', models.CharField(blank=True, choices=[('CC', 'Credit/Debit Card'), ('NB', 'Net Banking'), ('UPI', 'UPI'), ('COD', 'Cash on Delivery')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preferred_address', to='orders.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment Preference',
                'verbose_name_plural': 'Payment Preferences',
                'db_table': 'payment_preferences',
            },
        ),
        migrations.CreateModel(
            name='SavedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_nickname', models.CharField(blank=True, max_length=100)),
                ('last_four_digits', models.CharField(max_length=4)),
                ('card_type', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('is_preferred', models.BooleanField(default=False)),
                ('razorpay_card_id', models.CharField(blank=True, help_text='Razorpay card token/ID', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Card',
                'verbose_name_plural': 'Saved Cards',
                'db_table': 'saved_cards',
                'ordering': ['-is_preferred', '-created_at'],
            },
        ),
    ]
